services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/server/src
      - ./shared/src:/app/shared/src
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/client/src
      - ./client/index.html:/app/client/index.html
      - ./client/tsconfig.json:/app/client/tsconfig.json
      - ./client/vite-env.d.ts:/app/client/vite-env.d.ts
      - ./client/vite.config.ts:/app/client/vite.config.ts
      - ./client/vite:/app/client/vite
      - ./shared/src:/app/shared/src
      - client_node_modules:/app/client/node_modules
    environment:
      - VITE_SERVER_URL=ws://localhost:3000/ws
    depends_on:
      - server
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mmo_game

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  client_node_modules: 